#!/bin/bash
# Installs packages that are useful for a full dev environment.
# Currently targeted at 14.04

echo "Installs packages that are useful for My development environment." 
echo "Currently targeted at Linux Mint 14.04"
echo " "

#----------------Main Installs----------------
sudo apt-get install cmake
apt-get install cups-pdf
apt-get install firefox
apt-get install git
apt-get install gitk
apt-get install nautilus-dropbox
apt-get install python-uniconvertor
apt-get install ubuntu-restricted-extras
apt-get install unity 
sudo chmod 777 /dev/ttyACM0
cd /home/david

# Wine 
#sudo apt-get install wine
#sudo apt-get install wine-mono
#sudo apt-get install wine-gecko

# Google Chrome
apt install google-chrome-stable
cd /home/david/Desktop
touch Google_Chrome.desktop
echo "[Desktop Entry]
Version=1.0
Name=Google Chrome
GenericName=Web Browser
Comment=Access the Internet
Exec=/usr/bin/google-chrome-stable %U
Terminal=false
Icon=google-chrome
Type=Application
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
X-Ayatana-Desktop-Shortcuts=NewWindow;NewIncognito
[NewWindow Shortcut Group]
Name=New Window
Exec=/usr/bin/google-chrome-stable
TargetEnvironment=Unity
[NewIncognito Shortcut Group]
Name=New Incognito Window
Exec=/usr/bin/google-chrome-stable --incognito
TargetEnvironment=Unity
" >>  Google_Chrome.desktop
chmod 777  Google_Chrome.desktop

# OpenCV
#echo "Installing OpenCV"
#apt-get install build-essential
#apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
#apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
#apt-get install libopencv-dev
#apt-get install python-opencv

# Arduino IDE
echo "Installing Arduino IDE"
cd /home/david
wget https://www.arduino.cc/download.php?f=/arduino-nightly-linux64.tar.xz
tar -xf download.php?f=%2Farduino-nightly-linux64.tar.xz
cd /home/david/arduino-nightly
chmod 777 install.sh
sh install.sh
cd /home/david
rm download.php?f=%2Farduino-nightly-linux64.tar.xz
cd /home/david/Desktop
touch arduino.desktop
echo "[Desktop Entry]
Type=Application
Name=Arduino IDE
GenericName=Arduino IDE
Comment=Open-source electronics prototyping platform
Exec=/home/david/arduino-nightly/arduino
Icon=arduino-arduinoide
Terminal=false
Categories=Development;IDE;Electronics;
MimeType=text/x-arduino;
Keywords=embedded electronics;electronics;avr;microcontroller;
StartupWMClass=processing-app-Base
Name[en_CA]=Arduino" >> arduino.desktop
chmod 777 arduino.desktop
rm ~/Desktop/arduino-arduinoide.desktop
sudo 
cd /dev chmod 777 ttyACM0

# Openscad
echo "Installing OpenScad" 
sudo add-apt-repository -y ppa:openscad/releases
sudo apt-get update
sudo apt-get install openscad
cd /home/david/Desktop
touch openscad.desktop
echo " 
[Desktop Entry]
Type=Application
Version=1.0
Name=OpenSCAD
Icon=/usr/share/pixmaps/openscad.png
Exec=openscad %f
MimeType=application/x-openscad;
Categories=Graphics;3DGraphics;Engineering;
Terminal=false">> openscad.desktop
chmod 777 openscad.desktop

# DXF2Gcode
#sudo apt_get install unzip
#wget https://github.com/workflo/dxf2gcode/archive/master.zip
#unzip master.zip
#rm master.zip
#mv /home/david/dxf2gcode-master /home/david/dxf2gcode
#cd /home/david/Desktop
#touch DXF2Gcode.desktop
#echo "
#[Desktop Entry]
#Comment=
#Terminal=false
#Name=DXF2Gcode
#Exec=/home/david/dxf2gcode/source/dxf2gcode.py
#Type=Application
#Icon=/home/david/dxf2gcode/source/images/dxf2gcode_logo.png
#">> DXF2Gcode.desktop
#chmod 777 DXF2Gcode.desktop

# IDLE 2.7 & IDLE 3.4
sudo apt-get install python
sudo apt-get install python-pygame
sudo apt-get install idle 2.7
sudo apt-get install idle 3.4
#sudo apt-get install build-essential
#sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
#sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
sudo apt-get install python-pip
pip install pygame
cd /home/david/Desktop
touch IDLE_2.7.desktop
echo "
[Desktop Entry]
Name=IDLE (using Python-2.7)
Comment=Integrated Development Environment for Python (using Python-2.7)
Exec=/usr/bin/idle-python2.7
Icon=/usr/share/pixmaps/python2.7.xpm
Terminal=false
Type=Application
Categories=Application;Development;
StartupNotify=true
Name[en_CA]=IDLE 2.7" >> IDLE_2.7.desktop
chmod 777 IDLE_2.7.desktop
cd /home/david/Desktop
touch IDLE_3.4.desktop
echo "
[Desktop Entry]
Name=IDLE_3.4
Comment=Integrated Development Environment for Python (using Python-3.4)
Exec=/usr/bin/idle-python3.4
Icon=/usr/share/pixmaps/python3.4.xpm
Terminal=false
Type=Application
Categories=Application;Development;
StartupNotify=true" >> IDLE_3.4.desktop
chmod 777 IDLE_3.4.desktop
		
# Eagle 7.6.0
echo "Installing Eagle 7.6.0"
apt-get install libcrypto++9:i386
apt-get install libfontconfig:i386
apt-get install libssl1.0.0:i386 
apt-get install libxcursor1:i386  
apt-get install libxi6:i386 
apt-get install libxrender1:i386 
apt-get install libxrandr2:i386  
wget http://web.cadsoft.de/ftp/eagle/program/7.6/eagle-lin64-7.6.0.run
sh eagle-lin64-7.6.0.run
rm eagle-lin64-7.6.0.run
mv /home/david/eagle-7.6.0 /home/david/eagle
cd /home/david/Desktop
touch eagle.desktop
echo "[Desktop Entry]
Categories=Development;Engineering;Electronics;
Comment=Design a printed circuit board.
Exec=/home/david/eagle/bin/eagle
GenericName=PCB Designer
Icon=/home/david/eagle/bin/eagleicon50.png
MimeType=application/vnd.cadsoft.eagle.board;application/vnd.cadsoft.eagle.project;application/vnd.cadsoft.eagle.schematic
Name=Eagle
Type=Application
Terminal=false" >> eagle.desktop
chmod 777 eagle.desktop

# Inkscape
sudo apt-get install inkscape
cd /home/david/Desktop
touch inkscape.desktop
echo "[Desktop Entry]
Version=1.0
Name=Inkscape
GenericName=Vector Graphics Editor
X-GNOME-FullName=Inkscape Vector Graphics Editor
Comment=Create and edit Scalable Vector Graphics images
Type=Application
Categories=Graphics;VectorGraphics;GTK;
MimeType=image/svg+xml;image/svg+xml-compressed;application/vnd.corel-draw;application/pdf;application/postscript;image/x-eps;application/illustrator;
Exec=inkscape %F
TryExec=inkscape
Terminal=false
StartupNotify=true
Icon=inkscape
X-Ayatana-Desktop-Shortcuts=Drawing
[Drawing Shortcut Group]
Name=New Drawing
Exec=inkscape
TargetEnvironment=Unity" >> inkscape.desktop
chmod 777 inkscape.desktop

# Pinta paint program
cd /home/david
sudo apt-get install pinta
cd /home/david/Desktop
touch Pinta.desktop
echo "[Desktop Entry]
Name=Pinta
Comment=Easily create and edit images
GenericName=Image Editor
X-GNOME-FullName=Pinta Image Editor
Exec=pinta %F
Icon=pinta
StartupNotify=false
Terminal=false
Type=Application
Categories=Graphics;2DGraphics;
MimeType=image/bmp;">> Pinta.desktop
chmod 777 Pinta.desktop

# Java8 program
cd /home/david
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
cd /home/david

# Universal G-code Sender
cd /home/david
wget http://bit.ly/1M6z2ys
cd /home/david
mkdir /home/david/Universal_G-Code_Sender
unzip 1M6z2ys -d /home/david/Universal_G-Code_Sender
cd /home/david
rm /home/david/1M6z2ys
cd /home/david/Universal_G-Code_Sender
chmod 777 start-windows.bat
chmod 777 start.sh
cd /home/david/Universal_G-Code_Sender
wget https://raw.githubusercontent.com/DoomsdayRobots/Scripts/master/UGS_Icons/UGS_48x48.png

cd /home/david/Desktop
touch Universal_G-code_Sender.desktop
echo "
[Desktop Entry]
Comment=
Terminal=true
Name=Universal_G-Code_Sender
Exec=/home/david/Universal_G-Code_Sender/start.sh
Type=Application
Icon=/home/david/Universal_G-Code_Sender/UGS_48x48.png
" >> Universal_G-code_Sender.desktop
chmod 777 Universal_G-code_Sender.desktop
cd /home/david


#----------------Folder creator----------------
echo "This is the Script 'Find'" 
if [ -d Cad_Stuff] 
then 
    echo "Found the file 'Cad_Stuff'"
else 
    echo "Could not find the file 'Cad_Stuff'"
    mkdir Cad_Stuff
    echo ""
    echo "Created the file 'Cad_Stuff'"
fi

if [ -d Programing_Stuff ] 
then 
    echo "Found the file 'Programing_Stuff'"
else 
    echo "Could not find the file 'Programing_Stuff'"
    mkdir Programing_Stuff
    echo ""
    echo "Created the file 'Programing_Stuff'"
fi

if [ -d Electronic_Stuff ] 
then 
    echo "Found the file 'Electronic_Stuff'"
else 
    echo "Could not find the file 'Electronic_Stuff'"
    mkdir Electronic_Stuff
    echo ""
    echo "Created the file 'Electronic_Stuff'"
fi
