#!/bin/bash
# Install python modules for python 3

echo "Install python modules for python 3" 
echo " "

sudo apt-get install --assume-yes update

echo "Attempting to install and upgrade pip".


python3 -m pip install --upgrade pip

echo " Some basics..."
echo " "
echo " "
echo " Now trying to install:"
echo "    Setup Tools"
echo "    numpy"
echo "    matplotlib"
echo "    pypi"
echo "    scipy"
echo "    pygame"
echo "    beautifulsoup4"

python3 -m pip install setuptools
python3 -m pip install numpy
python3 -m pip install matplotlib
python3 -m pip install pypi
python3 -m pip install scipy
python3 -m pip install pygame
python3 -m pip install beautifulsoup4

echo " "
echo " "
echo " Now trying to install:"
echo "    Open GL"
echo "    openCV"
echo "    Crypto"

python3 -m pip install PyOpenGL 
python3 -m pip install opencv-contrib-python  
python3 -m pip install crypto  

echo " "
echo " "
echo " Now attempting to install Kivy"
echo " "
echo " "
python3 -m pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/

python3 -m pip install kivy-garden
python3 -m pip install urllib3

python3 -m pip install pillow
python3 -m pip install lxml
python3 -m pip install jupyter

echo " "
echo " "
echo "Done attempting to install everything! "
echo " "
echo " "

