#!/bin/bash
# Install python modules for python 3

echo " "
echo " "
echo "Install python modules for python 3" 
echo " "
echo " "
sudo apt-get install --assume-yes update

echo " "
echo " "
echo "Attempting to install and upgrade pip".
echo " "
echo " "

python3 -m pip install --upgrade pip

echo " Some basics..."
echo " "
echo " "
echo " Now trying to install:"
echo "    Setup Tools"
echo "    numpy"
echo "    matplotlib"
echo "    pypi"
echo "    scipy"
echo "    pygame"
echo "    beautifulsoup4"
echo "    brew"
echo " "
echo " "

python3 -m pip install setuptools
python3 -m pip install numpy
python3 -m pip install matplotlib
python3 -m pip install pypi
python3 -m pip install scipy
python3 -m pip install pygame
python3 -m pip install beautifulsoup4
python3 -m pip install brew

echo " "
echo " "
echo " Now trying to install:"
echo "    Open GL"
echo "    install numpy-stl"
echo "    openCV"
echo "    Crypto"
echo " "
echo " "

python3 -m pip install PyOpenGL 
python3 -m pip install numpy-stl
python3 -m pip install opencv-contrib-python  
python3 -m pip install crypto  

echo " "
echo " "
echo " Now attempting to install G-Code related things..."
echo "    gcodeutils"
echo "    pypandoc"
echo "    pycnc"
echo "    grbl-link"
echo "    makerbot_driver"
echo "    fabby"
echo "    gcody"
echo " "
echo " "

python 3 -m pip install gcodeutils
python 3 -m pip install pypandoc
python 3 -m pip install pycnc
python 3 -m pip install grbl-link
python 3 -m pip install makerbot_driver
python 3 -m pip install fabby
python 3 -m pip install gcody

echo " "
echo " "
echo " Now attempting to install Text To speach related things..." 
echo "    watson_tts_py"
echo "    tts-watson"
echo " "
echo " "

python 3 -m pip install watson_tts_py
python 3 -m pip install tts-watson

echo " "
echo " "
echo " Now attempting to install Kivy"
echo " "
echo " "

python3 -m pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/

python3 -m pip install kivy-garden
python3 -m pip install urllib3

python3 -m pip install pillow
python3 -m pip install lxml
python3 -m pip install jupyter

echo " "
echo " "
echo "Done attempting to install everything! "
echo " "
echo " "

