#!/bin/bash

#----------------Folder creator----------------

echo ""
echo "This is an installer and updater of Python3.10.2"
echo "This is also attempts to upgrade from"
echo "Python 2 ~to~ Python 3"
echo ""
echo "It also installs pip and idle for both versions of python"
echo ""
echo ""

echo ""
echo ""
echo "Ok lets work on installing things for Python 2"
echo ""
echo ""

sudo apt-get update
sudo apt-get install python-pip
sudo apt-get install idle

echo " "
echo " "
echo " This next bit is a Python PIP package module installer"
echo " for Linux mint 19. It includes packages and modules you"
echo " you use the most for Python2.4"
echo " "
echo ""

echo ""
echo ""
echo "searching for an installed version of 'Python 2'"
echo ""
echo ""

cd /usr/bin/
if [ -f python2 ]
then
    cd /home/david
    echo ""
    echo ""
    echo "Found the folder 'Python2'"
    echo ""
    echo ""    
    echo "pip main things"
    echo ""
    echo ""
    python -m pip install --upgrade pip
    python -m pip install setuptools
    python -m pip install wheel
    python -m pip install pypi
    python -m pip install --upgrade pip
    echo ""
    echo ""  
    echo "pip periferials"
    echo ""
    echo ""  
    python -m pip install keyboard
    python -m pip install serial --no-warn-script-location
    python -m pip install joystick
    python -m pip install camera
    python -m pip install servo
    echo ""
    echo ""  
    echo "pip math"
    echo ""
    echo ""  
    python -m pip install numpy --no-warn-script-location
    python -m pip install matplotlib
    python -m pip install scipy
    echo ""
    echo ""  
    echo "pip games"
    echo ""
    echo ""  
    python -m pip install pygame
    #python -m pip install tkinter
    python -m pip install pyopengl
    echo ""
    echo ""  
    echo "pip opencv and some other stuff"
    echo ""
    echo ""  
    python -m pip install opencv-python
    python -m pip install arduino
    #python -m pip install tensorflow
    echo ""
    echo ""  
    echo "pip web stuff"
    echo ""
    echo ""  
    python -m pip install urllib3
    python -m pip install beautifulsoup4
    python -m pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/
    python -m pip install kivy-garden
    echo ""
    echo ""  
    echo "pip installing CNC and stl related Things"
    echo ""
    echo ""  
    python -m pip install gcodeutils --no-warn-script-location
    python -m pip install pypandoc
    python -m pip install pycnc
    python -m pip install grbl-link --no-warn-script-location
    python -m pip install fabby --no-warn-script-location
    python -m pip install gcody
    python -m pip install numpy-stl --no-warn-script-location
    python -m pip install rsa
    python -m pip install humanize-gcode
    python -m pip install pillow

else
    cd /home/david
    echo ""
    echo ""   
    echo "OK. We won't proceed with anythng to do with python 2'"
    echo ""
    echo ""  
fi



echo ""
echo ""
echo "Ok now lets start working on installing Python 3"
echo ""
echo ""



echo ""
echo ""
echo "searching for an installed version of 'Python 3'"
echo ""
echo ""

cd /usr/bin/
if [ -f python3 ]
then
    cd /home/david
    echo ""
    echo ""
    echo "Found the folder 'Python3'"
    echo ""
    echo ""
    echo " This next bit is a Python PIP package module installer"
    echo " for Linux mint 19. It includes packages and modules you"
    echo " you use the most for Python3.6"
    echo ""
    echo ""    
    echo "pip main things"
    echo ""
    echo ""
    python3 -m pip install --upgrade pip
    python3 -m pip install setuptools
    python3 -m pip install wheel
    python3 -m pip install pypi
    python3 -m pip install --upgrade pip
    echo ""
    echo ""
    echo "pip periferials"
    echo ""
    echo ""
    python3 -m pip install keyboard
    python3 -m pip install serial --no-warn-script-location
    python3 -m pip install joystick
    python3 -m pip install camera
    python3 -m pip install servo
    echo ""
    echo ""
    echo "pip math"
    echo ""
    echo ""
    python3 -m pip install numpy --no-warn-script-location
    python3 -m pip install matplotlib
    python3 -m pip install scipy
    echo ""
    echo ""
    echo "pip games"
    echo ""
    echo ""
    python3 -m pip install pygame
    #python3 -m pip install tkinter
    python3 -m pip install pyopengl
    echo ""
    echo ""
    echo "pip opencv and some other stuff"
    echo ""
    echo ""
    python3 -m pip install opencv-python
    python3 -m pip install arduino
    #python3 -m pip install tensorflow
    echo ""
    echo ""
    echo "pip web stuff"
    echo ""
    echo ""
    python3 -m pip install urllib3
    python3 -m pip install beautifulsoup4
    python3 -m pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/
    python3 -m pip install kivy-garden
    echo ""
    echo ""
    echo "pip installing CNC and stl related Things"
    echo ""
    echo ""
    python3 -m pip install gcodeutils --no-warn-script-location
    python3 -m pip install pypandoc
    python3 -m pip install pycnc
    python3 -m pip install grbl-link --no-warn-script-location
    python3 -m pip install fabby --no-warn-script-location
    python3 -m pip install gcody
    python3 -m pip install numpy-stl --no-warn-script-location
    python3 -m pip install rsa
    python3 -m pip install humanize-gcode
    python3 -m pip install pillow
else
    cd /home/david
    echo ""
    echo ""   
    echo "No version of Python 3 currently installed"
    echo "Lets rectify that right now!"
    echo ""
    echo ""  
    echo "prepairing to install python3.10.2"
    echo ""
    echo ""
    sudo apt-get update
    sudo apt-get install python3.10
    sudo apt-get upgrade python3

    sudo apt-get install idle3
    sudo apt-get upgrade idle3

    sudo apt-get install python3-pip
    sudo apt-get upgrade python3-pip
    echo ""
    echo ""
    echo "Their! Now that we have installed Python 3"
    echo "we can start to install the pip related things"
    echo ""
    echo ""
    echo " This next bit is a Python PIP package module installer"
    echo " for Linux mint 19. It includes packages and modules you"
    echo " you use the most for Python3.6"
    echo ""
    echo ""  
    echo "pip main things"
    echo ""
    echo ""
    python3 -m pip install --upgrade pip
    python3 -m pip install setuptools
    python3 -m pip install wheel
    python3 -m pip install pypi
    python3 -m pip install --upgrade pip
    echo ""
    echo ""
    echo "pip periferials"
    echo ""
    echo ""
    python3 -m pip install keyboard
    python3 -m pip install serial --no-warn-script-location
    python3 -m pip install joystick
    python3 -m pip install camera
    python3 -m pip install servo
    echo ""
    echo ""
    echo "pip math"
    echo ""
    echo ""
    python3 -m pip install numpy --no-warn-script-location
    python3 -m pip install matplotlib
    python3 -m pip install scipy
    echo ""
    echo ""
    echo "pip games"
    echo ""
    echo ""
    python3 -m pip install pygame
    #python3 -m pip install tkinter
    python3 -m pip install pyopengl
    echo ""
    echo ""
    echo "pip opencv and some other stuff"
    echo ""
    echo ""
    python3 -m pip install opencv-python
    python3 -m pip install arduino
    #python3 -m pip install tensorflow
    echo ""
    echo ""
    echo "pip web stuff"
    echo ""
    echo ""
    python3 -m pip install urllib3
    python3 -m pip install beautifulsoup4
    python3 -m pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/
    python3 -m pip install kivy-garden
    echo ""
    echo ""
    echo "pip installing CNC and stl related Things"
    echo ""
    echo ""
    python3 -m pip install gcodeutils --no-warn-script-location
    python3 -m pip install pypandoc
    python3 -m pip install pycnc
    python3 -m pip install grbl-link --no-warn-script-location
    python3 -m pip install fabby --no-warn-script-location
    python3 -m pip install gcody
    python3 -m pip install numpy-stl --no-warn-script-location
    python3 -m pip install rsa
    python3 -m pip install humanize-gcode
    python3 -m pip install pillow
fi

cd /usr/bin/
if [[ -f python2 && -f python3 ]] 
then
    cd /home/david
    echo ""
    echo ""
    echo "Ok good Python2 and python3 are installed"
    echo "Lets convert from using Python 2 for" 
    echo "our main version of python to using"
    echo "Python 3 as our main version of Python"
    echo ""
    echo ""

    sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.6 2
    sudo update-alternatives --list python
    "2" | sudo update-alternatives --config python

    echo " "
    echo " "  
    sudo python --version  
    echo " "
    echo " "  
fi


